# Generated by Django 3.0.8 on 2020-07-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vladelets', models.TextField(max_length=60, verbose_name='Владелец')),
                ('chet', models.PositiveIntegerField(max_length=10, verbose_name='Номер счета')),
                ('balance', models.PositiveIntegerField(max_length=100, verbose_name='Баланс')),
            ],
        ),
    ]
