# Generated by Django 3.0.8 on 2020-07-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trn',
            name='chet',
        ),
        migrations.AddField(
            model_name='trn',
            name='schet',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trn',
            name='balance',
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trn',
            name='vladelets',
            field=models.TextField(max_length=60, verbose_name='Пользователь №1'),
        ),
    ]
