# Generated by Django 3.0.8 on 2020-07-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200729_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='balance',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='vladelets',
            field=models.TextField(max_length=60),
        ),
    ]
