# Generated by Django 3.0.8 on 2020-07-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200729_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='schet',
            field=models.PositiveIntegerField(),
        ),
    ]
